### ISSUE TITLE
Add GeoScience Macquarie grids

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDataCentre/raadsync#14]
http://www.ga.gov.au/metadata-gateway/metadata/record/gcat_b9224f95-a416-07f8-e044-00144fdd4fa6/XYZ+multibeam+bathymetric+grids+of+the+Macquarie+Ridge

Suggest using the ArcGIS-grid (but not sure what the CSAR format is, some FME thing).

**Comment by mdsumner** [comment]
Added to local on raadsync as "Geoscience Australia XYZ multibeam bathymetric grids of the Macquarie Ridge"

**Comment by mdsumner** [comment]
This is tested and now in raadtools dev. Please port to default config: 

"Geoscience Australia XYZ multibeam bathymetric grids of the Macquarie Ridge",

**Comment by raymondben** [comment]
Done (v0.27).
