### ISSUE TITLE
fixes, license, please review and enable travis for nice green badge

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDataCentre/raadsync#22]
I fixed a few things

- readme.rmd
- updated the license details as per devtools (please check this is ok "MIT + LICENSE")
- added travis
- added testthat stub (balked when I couldn't get repo_summary to run, it can wait)
- namespace additions (import from utils) for R 3.3.0

Can you enable travis for this? I've added the badge already. 

Go to https://travis-ci.org/profile/profile and click raadsync on

Also, do this if you can be bothered: http://itsalocke.com/using-travis-make-sure-use-github-pat/

**Comment by raymondben** [comment]
repo_summary updated to use rmarkdown::render, works now (v 0.30.9003)

**Comment by raymondben** [comment]
Travis enabled, PAT added
