### ISSUE TITLE
file sizes from oceandata?

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDataCentre/raadsync#36]
When you use this interactively, you get a file size: 

https://oceandata.sci.gsfc.nasa.gov/search/file_search.cgi

How to do that with wget?

**Comment by raymondben** [comment]
Not trivially! That search API doesn't have an option to return file size (see https://oceandata.sci.gsfc.nasa.gov/search/file_search.cgi). You could do it by searching for the files you want and then for each one fetch the headers only, e.g.:

curl -I https://oceandata.sci.gsfc.nasa.gov/cgi/getfile/A2002184.L3m_DAY_CHL_chlor_a_9km.nc

The content-length field in the headers should hopefully be informative ...

**Comment by mdsumner** [comment]
Cool, that helps thanks!
