### ISSUE TITLE
add memoization to SHA-1 checks

### ISSUE THREAD

**Issue by mdsumner** [AustralianAntarcticDataCentre/raadsync#4]
Something like

```R
library(R.cache) ## on first use it asks where to put the cache
sha1 <- function(filename) {
  # 1. Try to load cached data, if already generated
       key <- list(filename)
       data <- loadCache(key)
       if (!is.null(data)) {
         # cat("Loaded cached data\n")
         return(data);
       }
     
       # 2. If not available, generate it.
      #  cat("Generating data from scratch...")
       data <- digest_or_openssl(filename)
       saveCache(data, key=key, comment="8 days a week")

       data;
     }
     
}
```

**Comment by raymondben** [comment]
I think it's simpler than that: we can just create a wrapper around the `digest_or_openssl()` function with automatic caching:

```R
library(R.cache)
setCacheRootPath(cache_directory) #optionally set cache location directly
cached_sha1=addMemoization(digest_or_openssl)
```

Now, simply calling `cached_sha1(...)` will retrieve the result from the cache, if it exists, or compute and cache it, if not. Some diligence is still needed to ensure that the cache is kept up to date, though.

**Comment by raymondben** [comment]
Done in v0.28. On Linux at least, openssl-based SHA calculation is already pretty fast, so I don't think this will make much difference. But on Windows it may make a more noticeable improvement.
